<?php 

		function new_page_menu() {
     $items = array();
     $items['forsinel'] = array(
        'title'             =>  'forsinel Page',  //page title
        'description'       =>  'forsinel Information',  //description show when mouse hover on link
        //'type' => MENU_NORMAL_ITEM, // add in the custom menu like a link
        'page callback'     =>  'forsinel_page_create',  //callback function which is invoked when menu item is called.
        'access callback'   =>  true,  //any user can access this page
       );
      return $items;
    }


    /*
* implement hook_theme()
*/
    function new_page_theme() {
            $themes = array();
            $themes['forsinel_page'] = array(
            'variables' => array(),
            'template' => 'templates/forsinel_page',
            'path' => drupal_get_path('module', 'new_page'),
          );
         return $themes;

    }


        /*
    * implement page callback()
    */
    function forsinel_page_create() {
      return theme('forsinel_page');
    }




